language: java

jdk:
  - openjdk11

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "cwz60rHpaBPWEubs0IStG7m6tp1LUHNQuJHBMhjOKdHQ7yXS+nyYEnVUJNN3hKLHzOE6M9Qq/0YmGfQvMwAQejsI7Iv71yarlvh67axCw/2fnPRcpmB8vTJ1ldxPa5fJNJ/Xssl+AGd2YaaD4WTpbWKpSZ/oTtHr2JpWUGoMC8I+40f9NDxSqDg0gMO1n3LMTO0Flpzs+nnuUsUSON/PDwDoCCtGYwh3vs7XuxkvHb2kpMsPXZ15v08M13MqFX2N2qV2l+qU8qDh1UdGgyenJrbrNAKXjS6ycEwDgGtY3o+0cvljxC2XoZ5jPMccPM+iXzP6MOS257795JjDbhyFLZca8feuea3p7/SoIYS9ltBrfj9n8AnPbHzg2tPP4Q4OMyv0VjhRVAJvQepEZZMtAnSlcLZJis6P3EaOjTwYx4oqb5xfLmrq7VR7RSo9jOjMP8TMNS5kRBxrKlEclVJRUyDQydTeJu7TXliGcydzVd5hsAPsUWckT22PtAYBAldqFKkp+3PrCNVYh3e90WSVZSlQdLluMw2OvO1wlOEC+BVU8gRURIuQshWlvlLCMvrhWXjMWqDPyyhKLZuMJN+YUlvZZCKCgKs//Xb8iailR8/KuQP0T9OBzYrSBARlg642QE+9Tk54nDEwRU5j1FV48xmvlRbzqjSW4P/D20WceMQ="
    - secure: "SLEDSSUaxajRkStwFCyMW5siuN3aUzNJh6mW0sb9LL5IjmvySN6E9+Wd8bcsitmAP26d1m4N+MdewceAJrhYgPAMEfWdPrzcLTnVYH4cjAMUguwNkcr+IqudaJp6wVWnylxv2bqRXKxi/An7c8KPvsG+CKaN+wyI91vsXzN8CEqMk0+2xwP0suL7cLcrAHJf13UgQtQXo5i/cmf+rDmMVrhUmqekn8NsCA0dEEyKjHnt/r3on5XFldntuxmze8Twz9fvMunht2MsE7HbiVA7ECLY3oxh3XVCci5QGwOb4uSD8qmLdWSlM+7olJXj8tbu38jHSF2nktgVnEBMGdt4wBWtJfcj5jbXwpGHpKaL662tDsPuwCuWc0VBWOwZT30o0BSiPzu82+S80qqPaFsCRi0XW5bslTt8fzF4XeiTN4YiLB10KBwSgZC8w3813VXZOgTawlb+biGDFNJ8gEGY0JiIuVQzH6NcT2z88gH2kUnARt8bpNFBHSULBDB+84m0t/rKG56N5oyF87/WUtqqsRaphyvWitZ7s+Rg1pAA6EtDuCKcVXo3Seqh+6rG6QlWkET+E6lEnRXupr+L5fKZL6jtlofsMHwwTUFO+1Jq0uwP8Vm+8xL8zKe2BvjuD2ICo4yTx3mLFc65/nTsl9GrngrU1nxXDxEQp7hsgLuWRRw="

branches:
  except:
    - gh-pages

notifications:
  email: false
